process.env.SAKAN_FAKE_FS = '1';
const { handle } = await import('../lib/handler.js');

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log('  \u2713 ' + m); } else { fail++; console.log('  \u2717 ' + m); } };
const call = (method, path, { token = null, body = {} } = {}) => handle({ method, path, body, token });

console.log('\n— Pairing —');
const a = await call('POST', ['pair'], { body: { email: 'm@x', displayName: 'مصطفى' } });
ok(a.status === 200 && a.body.pairCode, 'Mustafa creates a pair');
const A = a.body.token;
const b = await call('POST', ['pair', 'join'], { body: { code: a.body.pairCode, email: 'd@x', displayName: 'ضحى' } });
ok(b.status === 200 && b.body.pairId === a.body.pairId, 'Doaa joins same pair');
const B = b.body.token;

console.log('\n— J1 flow —');
const r = await call('POST', ['resources'], { token: A, body: { title: 'مورد', sourceText: 'الزواج ميثاق غليظ. يقوم على المودة. وله حقوق وواجبات.' } });
ok(r.status === 200 && r.body.status === 'not_started', '1. add resource → not_started');
const rid = r.body.id;
await call('POST', ['resources', rid, 'summary'], { token: A });
const rdet = await call('GET', ['resources', rid], { token: A });
ok(rdet.body.resource.status === 'in_progress' && rdet.body.summary, '2. summary → in_progress');
const qs = await call('POST', ['resources', rid, 'questions', 'generate'], { token: A });
ok(qs.status === 200 && qs.body.length === 3 && qs.body[0].state === 'open', '3. questions → open');
const q1 = qs.body[0].id, q2 = qs.body[1].id, q3 = qs.body[2].id;
const a1 = await call('PUT', ['questions', q1, 'responses'], { token: A, body: { text: 'أ' } });
ok(a1.body.state === 'answered_by_one', '4. Mustafa answers → answered_by_one');
const peek = await call('GET', ['questions', q1, 'responses'], { token: B });
ok(peek.body.partner === null, '5. reveal rule: Doaa cannot see Mustafa answer yet');
const b1 = await call('PUT', ['questions', q1, 'responses'], { token: B, body: { text: 'ب' } });
ok(b1.body.state === 'ready_to_reveal', '   Doaa answers → ready_to_reveal');
const rev = await call('POST', ['questions', q1, 'reveal'], { token: A });
ok(rev.body.state === 'revealed', '6. reveal → revealed');
const both = await call('GET', ['questions', q1, 'responses'], { token: B });
ok(both.body.mine && both.body.partner, '   both visible after reveal');
const dec = await call('POST', ['decisions'], { token: A, body: { resourceId: rid, statement: 'نتفق', questionIds: [q1] } });
ok(dec.body.state === 'draft', '7. decision → draft');
const did = dec.body.id;
const c1 = await call('POST', ['decisions', did, 'confirm'], { token: A });
ok(c1.body.state === 'draft', '   1/2 confirm → still draft');
const c2 = await call('POST', ['decisions', did, 'confirm'], { token: B });
ok(c2.body.state === 'confirmed', '   2/2 confirm → CONFIRMED');
const after = await call('GET', ['resources', rid], { token: A });
ok(after.body.resource.status === 'completed', '   resource → completed');
ok(after.body.questions.find((x) => x.id === q1).state === 'decided', '   question → decided');

console.log('\n— Hardening —');
const log = await call('GET', ['decisions'], { token: B });
ok(log.body.length === 1 && log.body[0].state === 'confirmed', 'confirmed decision in log');
const ev = await call('GET', ['resources', rid, 'events'], { token: A });
ok(ev.body.some((e) => e.type === 'transition' && e.to === 'completed'), 'audit log has resource completion');
const force = await (async () => { await call('PUT', ['questions', q2, 'responses'], { token: A, body: { text: 'أ' } }); return call('POST', ['questions', q2, 'force-reveal'], { token: B }); })();
ok(force.body.revealMethod === 'force' && force.body.revealBy, 'force-reveal stored (method + who)');
const k = 'idem1';
const d1 = await call('POST', ['decisions'], { token: A, body: { resourceId: rid, statement: 'x', questionIds: [q1], idempotencyKey: k } });
const d2 = await call('POST', ['decisions'], { token: A, body: { resourceId: rid, statement: 'x', questionIds: [q1], idempotencyKey: k } });
ok(d1.body.id === d2.body.id, 'duplicate decision deduped by idempotency key');

console.log('\n— State + isolation —');
const bad = await call('POST', ['questions', q3, 'reveal'], { token: A });
ok(bad.status === 409, 'reveal on a not-ready question rejected (409)');
const c = await call('POST', ['pair'], { body: { email: 'o@x', displayName: 'تاني' } });
const C = c.body.token;
const cross = await call('GET', ['resources', rid], { token: C });
ok(cross.status === 404, 'another pair cannot read this resource (404)');
const clist = await call('GET', ['resources'], { token: C });
ok(Array.isArray(clist.body) && clist.body.length === 0, 'another pair sees nothing');
const noauth = await call('GET', ['resources'], {});
ok(noauth.status === 401, 'no token → 401');

console.log(`\nRESULT: ${pass} passed, ${fail} failed\n`);
process.exit(fail ? 1 : 0);
